### ISSUE TITLE
imm 构建失败

### ISSUE THREAD

**Issue by xunmoo** [fightroad/N1-OpenWrt#1]
大佬，imm 的n1构建失败，请查看下是什么原因哈？

**Comment by fightroad** [comment]
> 大佬，imm 的n1构建失败，请查看下是什么原因哈？

切换到23.05分支试试，原来是23.05分支但是kms插件编译报错。取消掉了。

**Comment by xunmoo** [comment]
> > 大佬，imm 的n1构建失败，请查看下是什么原因哈？
> 
> 切换到23.05分支试试，原来是23.05分支但是kms插件编译报错。取消掉了。

我再次精简了插件后跑出来了，使用24.10分支，不过imm这个好像没装中文语言包，我改成6.6内核版本的，加了语言包再跑看看
